model_id: "Qwen/Qwen3.5-4B"

model:
  name:                             "./models/qwen3.5-4b-lora-sft/"
  torch_dtype:                      "bfloat16"
  # load_in_8bit:                     True
  # llm_int8_threshold:               6.0
  # llm_int_skip_modules:             "none"
  # llm_int8_enable_fp32_cpu_offload: True
  attn_implementation:              "flash_attention_2"
  device_map:                       "cuda:0"
  trust_remote_code:                True

dataset:
  path:                             "./data/processed/primus_reasoning_cwe_mapping_dataset"
  max_length:                       4096  # max data has 4000 + tokens
  column:                           "messages"
  padding_side:                     "right"
  truncation_side:                  "left" 
  packing:                          False

lora_config: 
  r:                                32     # higher rank for larger models
  lora_alpha:                       64    # r * 2 is a common choice
  lora_dropout:                     0.05
  bias:                             "none"
  task_type:                        "CAUSAL_LM"
  use_rslora:                       True
  target_modules:                   [
    "q_proj", "k_proj", "v_proj", "o_proj",
    "gate_proj", "up_proj", "down_proj"
  ]

training:
  output_dir:                       "./checkpoints/qwen3.5-4b-rsft"
  logging_dir:                      "./logs/qwen3.5-4b-rsft"
  num_train_epochs:                 2
  per_device_train_batch_size:      4
  gradient_accumulation_steps:      2       # effective batch size = batch_size * accumulation_steps = 4 * 2 = 8
  learning_rate:                    2.0e-5  
  lr_scheduler_type:                "cosine"
  warmup_ratio:                     0.05
  weight_decay:                     0.02
  max_grad_norm:                    1.0
  optim:                            "paged_adamw_32bit"
  bf16:                             True
  fp16:                             False
  tf32:                             False
  dataloader_num_workers:           8
  dataloader_pin_memory:            True
  remove_unused_columns:            False
  logging_steps:                    20 # log every 20 steps
  report_to:                        "wandb"
  save_strategy:                    "steps"
  save_steps:                       20 # save checkpoint every 20 steps
  save_total_limit:                 3   # keep only the last 3 checkpoints
  load_best_model_at_end:           False
  assistant_only_loss:              True
  dataset_text_field:               "text"
  seed:                             42
  neftune_noise_alpha:              0.002

evaluation:
  model_path:                       "./models/qwen3.5-4b-lora-rsft/"
  output_dir:                       "./outputs/qwen3.5-4b/evaluation"
  torch_dtype:                      "bfloat16"
  trust_remote_code:                True
  use_cache:                        True
  padding:                          True
  truncation:                       True
  padding_side:                     "left"

wandb:      
  project:                          "cybersec-reasoner"
  run_name:                         "qwen3.5-4b-lora-rsft"
  entity:                           "circuit"
  tags:                             ["qwen3.5", "instruction tuned", "4b", "cold start", "pre grpo", "reasoning sft", "lora", "cybersecurity"]
  notes:                            "Reasoning Supervised Fine-tuning on Qwen3.5-4B SFT finetuned model with QLoRA on 1K Primus-Reasoning dataset with r=32, alpha=64, lr=2e-5, batch size=8."
  log_model:                        False

paths:      
  final_adapter_dir:                "./models/adapter/qwen3.5-4b-lora-rsft/"
  merged_model_dir:                 "./models/qwen3.5-4b-lora-rsft/"
  tokenizer_save_dir:               "./models/qwen3.5-4b-lora-rsft/"
  plots_dir:                        "./plots"